### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [Buckhead498/bwa-u4-feature-request#1]
### Criteria 1: Objective
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*:  Your objective is a good one.  It will help to reduce redundancy in the search results, which will make it easier to find and add new music.

### Criteria 2: Background
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your background section is good.  It provides a detailed explanation of the pain point this feature is addressing.  You also gave a good summary of the overall functionality and purpose of the feature within the app.

### Criteria 3: Technical Design
* **Score Level**: 3/4 (Meets Expectations)
* *Comment(s)*: You did well with your technical design section.  You described how you would modify the App component to include ways to filter the results to match those you desire to display.  Writing that method and including it would have been nice in order to view its implementation.  Great job!

### Criteria 4: Caveats
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did a good job thinking about the potential caveats of this feature.  Your proposal of changing the code at the request level in the Spotify utility was a good one.  I would also suggest thinking about the potential UX ramifications of a user expecting a result to be in the search, but it not appearing due to its existence within the playlist.  This could cause confusion.  It might be more appropriate to tag those results that already exist and display some visual cue versus purging them from the result set altogether.

### Overall Score: 15/16
Overall, you did a great job with this feature request.  You chose a feature that would greatly improve the UX of the app and explained the necessity for this feature clearly and concisely.  You also did well in detailing the specific aspects of the technical implementation and what caveats you might encounter with your initial implementation.  Nicely done!

**Comment by Buckhead498** [comment]
Thank you for your feedback
